/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cloud_computing;

import static cloud_computing.TASK_CREATION_ENCRYPTION.encryptedFilePath;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.CipherInputStream;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JOptionPane;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.Signature;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
//import org.bouncycastle.jce.spec.ECGenParameterSpec;
import javax.crypto.CipherOutputStream;
import java.security.Security;
import java.security.spec.ECGenParameterSpec;


/**
 *
 * @author admini
 */
public class Decryption_Homomorphic extends javax.swing.JFrame {

    /**
     * Creates new form Decryption_Homomorphic
     */
     String username = "";
     
     String dec_signature="";     
    public Decryption_Homomorphic() {
        initComponents();
         username = LiveLogin.txtUserName.getText().toString().trim();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jLabel1.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel1.setText("Decryption Of Data Using AES and ECC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(118, 118, 118))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jButton1.setText("Decryption Using AES and ECC");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(72, 72, 72))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String secretKey;
        try {
            decrypt();
        } catch (Exception ex) {
            Logger.getLogger(Decryption_Homomorphic.class.getName()).log(Level.SEVERE, null, ex);
        }
           String ss="";
        for(int zz=0;zz<TASK_CREATION_ENCRYPTION.vencrypt.size();zz++)
        {
            int dec=Integer.parseInt(TASK_CREATION_ENCRYPTION.vencrypt.get(zz).toString());
            int dec_val=decryption(dec);
        
            System.out.println("Dec Value"+dec_val );
            ss=ss+String.valueOf((char)(dec_val));
            
        }  
        
        System.out.println("Decrypted Value"+ss );
        /////////////////////Decrypted File Writing
 
        /////////////////////////
        
        
        String DecfileName =  "CloudStorage\\" + username + "\\FILES\\" + TASK_CREATION_ENCRYPTION.finame + "decrypted.txt.dec";

        try {
            
            // Assume default encoding.
            FileWriter fileWriter =
                new FileWriter(DecfileName);
            // Always wrap FileWriter in BufferedWriter.
            BufferedWriter bufferedWriter =
                new BufferedWriter(fileWriter);
            // Note that write() does not automatically
            // append a newline character.
            bufferedWriter.write(ss);
            // Always close files.
            bufferedWriter.close();
            
            JOptionPane.showMessageDialog(null ,"Decryption Successful" );
        }
        catch(IOException ex) {
            System.out.println(
                "Error writing to file" );
            // Or we could just do this:
            // ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    public void decrypt() throws Exception {
    // Opening streams
    String file1 =TASK_CREATION_ENCRYPTION.encfilename;
    Security.addProvider(new BouncyCastleProvider());
    String Encryption = "CloudStorage\\" + username + "\\" + "UploadFile\\";
    String filepath = TASK_CREATION_ENCRYPTION.encryptedFilePath;
    System.out.println("----********-----"+ filepath);

    // Encrypted file input paths
    String encryptedFilePath = filepath.replace("FILES", "VirtualMachine0") + ".enc";
    String encryptedKeyPath = filepath.replace("FILES", "VirtualMachine0") + ".des.key.enc";
    String signaturePath = filepath.replace("FILES", "VirtualMachine0") + ".file.signature";

    // Step 1: Load the encrypted AES key
    byte[] encryptedAesKey = Files.readAllBytes(Paths.get(encryptedKeyPath));

    // Step 2: Generate ECC Key Pair (for decryption)
    KeyPairGenerator ecKeyPairGen = KeyPairGenerator.getInstance("EC", "BC");
    ecKeyPairGen.initialize(new ECGenParameterSpec("secp256r1"));
    KeyPair ecKeyPair = ecKeyPairGen.generateKeyPair();
    PublicKey ecPublicKey = ecKeyPair.getPublic();
    PrivateKey ecPrivateKey = ecKeyPair.getPrivate();

    // Step 3: Decrypt the AES key using the ECC Private Key
    Cipher ecCipher = Cipher.getInstance("ECIES", "BC");
    ecCipher.init(Cipher.DECRYPT_MODE, ecPrivateKey);
    byte[] aesKeyBytes = ecCipher.doFinal(encryptedAesKey);
    SecretKey aesKey = new SecretKeySpec(aesKeyBytes, "AES");

    // Step 4: Decrypt the file using AES
    Cipher aesCipher = Cipher.getInstance("AES");
    aesCipher.init(Cipher.DECRYPT_MODE, aesKey);
    try (FileInputStream fis = new FileInputStream(encryptedFilePath);
         FileOutputStream fos = new FileOutputStream(filepath.replace(".enc", "_decrypted"));
         CipherOutputStream cos = new CipherOutputStream(fos, aesCipher)) {
        byte[] buffer = new byte[1024];
        int bytesRead;
        while ((bytesRead = fis.read(buffer)) != -1) {
            cos.write(buffer, 0, bytesRead);
        }
    }

    // Step 5: Verify the signature (optional)
    Signature signature = Signature.getInstance("SHA256withECDSA", "BC");
    signature.initVerify(ecPublicKey);
    try (FileInputStream efis = new FileInputStream(encryptedFilePath)) {
        byte[] buffer = new byte[1024];
        int bytesRead;
        while ((bytesRead = efis.read(buffer)) != -1) {
            signature.update(buffer, 0, bytesRead);
        }
    }
    byte[] digitalSignature = Files.readAllBytes(Paths.get(signaturePath));
    boolean isVerified = signature.verify(digitalSignature);

    if (isVerified) {
        System.out.println("File decrypted and signature verified successfully.");
    } else {
        System.out.println("Signature verification failed.");
    }
}

    
    
    
    
    
    
    
    
    
    
    
    public  void decrypt1() throws Exception{
String algo="DES/ECB/PKCS5Padding";
		//opening streams

String file1 =TASK_CREATION_ENCRYPTION.encfilename;
		FileInputStream fis =new FileInputStream(file1);
		File file=new File(file1+".dec");
		FileOutputStream fos =new FileOutputStream(file);               

		//generating same key
		byte k[] = "HignDlPs".getBytes();   
		
               System.out.println("Secret Key  "+k); 
               
		SecretKeySpec key = new SecretKeySpec(k,algo.split("/")[0]);  

               
		//creating and initialising cipher and cipher streams
		Cipher decrypt =  Cipher.getInstance(algo);  
		decrypt.init(Cipher.DECRYPT_MODE, key);  
		CipherInputStream cin=new CipherInputStream(fis, decrypt);

		byte[] buf = new byte[1024];
		int read=0;
		while((read=cin.read(buf))!=-1)  //reading encrypted data
			fos.write(buf,0,read);  //writing decrypted data

		//closing streams
		cin.close();
		fos.flush();
		fos.close();
                
                
                  File files = new File(file1);
         
        if(files.delete())
        {
            //System.out.println("File deleted successfully");
        }
        else
        {
           // System.out.println("Failed to delete the file");
        }

	}

    public static int decryption(int a){
        int val=0;
        
        
        if(a>78)
        {    
        
        val=a+13;
        
        }
        else
        {
            val=a-13;
        }    
        return val;
    }
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Decryption_Homomorphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Decryption_Homomorphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Decryption_Homomorphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Decryption_Homomorphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Decryption_Homomorphic().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
