/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cloud_computing;

import commoncodes.db_conn;
import java.io.File;
import java.util.Vector;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import javax.swing.JFileChooser;
import com.itextpdf.text.Document;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfImportedPage;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.parser.PdfTextExtractor;
import commoncodes.db_conn;
import java.awt.image.BufferedImage;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.security.*;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.CipherOutputStream;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import java.security.interfaces.ECPrivateKey;
import java.security.interfaces.ECPublicKey;
import java.security.spec.ECGenParameterSpec;

/**
 *
 * @author admini
 */
public class TASK_CREATION_ENCRYPTION extends javax.swing.JFrame {
 String str = "";
    public static String sd = "";
    public static String finame = "";
    public static String filepath = "";
    public static String filetype = "";
    //public static String Signature="";
    private String algo;
    private File file;
    String username = "";
    db_conn db = new db_conn();
    
    public static String encfilename="";
    String RBFHA = LiveLogin.RBFHA;//"DES/ECB/PKCS5Padding";
     public static Vector vencrypt=new Vector();
     
//     public static String encryptedFilePath="";
  public static String encryptedFilePath ="" ;
        public static String encryptedKeyPath ="";
        public static String signaturePath = "";
      public static Calendar cal = Calendar.getInstance();
    /**
     * Creates new form TASK_CREATION_ENCRYPTION
     */
    public TASK_CREATION_ENCRYPTION() {
        initComponents();
         username = LiveLogin.txtUserName.getText().toString().trim();
    }
//  public static Calendar cal = Calendar.getInstance();

    

    public TASK_CREATION_ENCRYPTION(String algo, String path) {
        this.algo = algo; //setting algo
        this.file = new File(path); //settong file
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbtasktype = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Select Application Type");

        cmbtasktype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TEXTFILE", "PDF" }));

        jButton1.setText("Effiecient Hybrid AES and ECC  Encryption ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("PROCESS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jProgressBar1.setIndeterminate(true);

        jButton4.setText("Decryption");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4)
                            .addComponent(jButton2))
                        .addGap(96, 96, 96)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbtasktype, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbtasktype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(28, 28, 28)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(34, 34, 34))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("****   APPLICATION CREATION  ****");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        try {

            if (cmbtasktype.getSelectedItem().toString().equalsIgnoreCase("PDF")) {
                new TASK_CREATION_ENCRYPTION(RBFHA, "CloudStorage\\" + username + "\\FILES\\" + finame + ".pdf").encrypt();

                filepath = "CloudStorage\\" + username + "\\FILES\\" + finame + ".txt";

                try {
                    Calendar cal2 = Calendar.getInstance();

                    long milliSec1 = cal2.getTimeInMillis();

                    try {
                        Thread.sleep(4000);
                    } catch (Exception e) {
                        e.printStackTrace();

                    }
                    long milliSec2 = cal.getTimeInMillis();

                    long timeDifInMilliSec;
                    if (milliSec1 >= milliSec2) {
                        timeDifInMilliSec = milliSec1 - milliSec2;
                    } else {
                        timeDifInMilliSec = milliSec2 - milliSec1;
                    }

                    long timeDifSeconds = timeDifInMilliSec / 1000;
                    long timeDifMinutes = timeDifInMilliSec / (60 * 1000);
                    long timeDifHours = timeDifInMilliSec / (60 * 60 * 1000);
                    long timeDifDays = timeDifInMilliSec / (24 * 60 * 60 * 1000);

                    File file1 = new File("CloudStorage\\" + username + "\\FILES\\" + finame + ".txt");
                    double megabytes = 0;
                    if (file1.exists()) {

                        double bytes = file1.length();
                        double kilobytes = (bytes / 1024);
                        megabytes = (kilobytes / 1024);

                    }







                    System.out.println("megabytes+++" + megabytes);
                    System.out.println("timeDifSeconds" + timeDifSeconds);
                    double throughput = megabytes / timeDifSeconds;
                    //double throughput=megabytes/timeDifInMilliSec;

                    String insert_Qry = "insert into tbl_performencecomparision(Algorithmname,Throughput) values( 'AES and RSA','" + throughput + "')";
                     System.out.println(insert_Qry);
                    System.out.println("Time differences expressed in various units are given below");

                      db.stmt12.executeUpdate(insert_Qry);
                    System.out.println(timeDifInMilliSec + " Milliseconds");
                    System.out.println(timeDifSeconds + " Seconds");
                    System.out.println(timeDifMinutes + " Minutes");
                    System.out.println(timeDifHours + " Hours");
                    System.out.println(timeDifDays + " Days");

                } catch (Exception ex) {
                    //Logger.getLogger(ENCRYPTION.class.getName()).log(Level.SEVERE, null, ex);
                    ex.printStackTrace();
                }

//                homomorphic();
                JOptionPane.showMessageDialog(null, "TASK Encryption Completed");
            } else {
                new TASK_CREATION_ENCRYPTION(RBFHA, "CloudStorage\\" + username + "\\FILES\\" + finame + ".txt").encrypt();

                filepath = "CloudStorage\\" + username + "\\FILES\\" + finame + ".txt";

                try {
                    Calendar cal2 = Calendar.getInstance();

                    long milliSec1 = cal2.getTimeInMillis();

                    try {
                        Thread.sleep(4000);
                    } catch (Exception e) {
                        e.printStackTrace();

                    }
                    long milliSec2 = cal.getTimeInMillis();

                    long timeDifInMilliSec;
                    if (milliSec1 >= milliSec2) {
                        timeDifInMilliSec = milliSec1 - milliSec2;
                    } else {
                        timeDifInMilliSec = milliSec2 - milliSec1;
                    }

                    long timeDifSeconds = timeDifInMilliSec / 1000;
                    long timeDifMinutes = timeDifInMilliSec / (60 * 1000);
                    long timeDifHours = timeDifInMilliSec / (60 * 60 * 1000);
                    long timeDifDays = timeDifInMilliSec / (24 * 60 * 60 * 1000);

                    File file1 = new File("CloudStorage\\" + username + "\\FILES\\" + finame + ".txt");
                    double megabytes = 0;
                    if (file1.exists()) {

                        double bytes = file1.length();
                        double kilobytes = (bytes / 1024);
                        megabytes = (kilobytes / 1024);

                    }







                    System.out.println("megabytes+++" + megabytes);
                    System.out.println("timeDifSeconds" + timeDifSeconds);
                    
                    String insert_qry1="insert into tbl_performenceexecutiontime(Algorithmname,Executionpertask) values('AES and RSA','" + timeDifSeconds + "')";
                    double throughput = megabytes / timeDifSeconds;
                    //double throughput=megabytes/timeDifInMilliSec;
                    db.stmt13.executeUpdate(insert_qry1);

                    String insert_Qry = "insert into tbl_performencecomparision(Algorithmname,Throughput) values( 'AES and RSA','" + throughput + "')";
                    System.out.println("Time differences expressed in various units are given below");

                    System.out.println(insert_Qry);
                    
                     db.stmt12.executeUpdate(insert_Qry);
                    System.out.println(timeDifInMilliSec + " Milliseconds");
                    System.out.println(timeDifSeconds + " Seconds");
                    System.out.println(timeDifMinutes + " Minutes");
                    System.out.println(timeDifHours + " Hours");
                    System.out.println(timeDifDays + " Days");

                } catch (Exception ex) {
                    //Logger.getLogger(ENCRYPTION.class.getName()).log(Level.SEVERE, null, ex);
                    ex.printStackTrace();
                }

              //  homomorphic();
                JOptionPane.showMessageDialog(null, "TASK Encryption Completed");


            }

            System.out.println("----path----" + filepath);

            File file11 = new File(filepath);

            if (file11.delete()) {
                System.out.println("File deleted successfully");
            } else {
                System.out.println("Failed to delete the file");
            }

        } catch (Exception ex) {
            Logger.getLogger(TASK_CREATION_ENCRYPTION.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed




        // print current time
        System.out.println(" Start time is : " + cal.getTime());
        filetype = cmbtasktype.getSelectedItem().toString();

        double starttime = System.nanoTime();
        if (cmbtasktype.getSelectedItem().toString().equalsIgnoreCase("PDF")) {

            try {
                JFileChooser fc = new JFileChooser();
                fc.setCurrentDirectory(new File("."));
                //fc.addChoosableFileFilter(new OnlyExt());
                fc.setAcceptAllFileFilterUsed(false);

                int returnval = fc.showOpenDialog(null);
                if (returnval == JFileChooser.APPROVE_OPTION) {
                    File file = fc.getSelectedFile();
                    sd = file.getPath();
                    finame = file.getName();

                    System.out.println(sd);
                    System.out.println();
                }



                PdfReader reader = new PdfReader(sd);//"D:\\M.E\\Saranya\\entity.pdf");
                int n = reader.getNumberOfPages();
                Rectangle psize = reader.getPageSize(1);
                Document document = new Document(psize);

                PdfReader reader1 = new PdfReader(sd);
                int n1 = reader1.getNumberOfPages();



                for (int i = 1; i <= n1; i++) {

                    System.out.println("Page  Number==>" + i);
                    String str = PdfTextExtractor.getTextFromPage(reader1, i);
                    System.out.println(str);
                }
//Pdf writeing


                PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("CloudStorage\\" + username + "\\" + "FILES\\" + finame + ".pdf"));
                document.open();
                for (int i = 1; i <= n1; i++) {
                    PdfContentByte pdf = writer.getDirectContent();
                    document.newPage();

                    PdfImportedPage page = writer.getImportedPage(reader, i);

                    pdf.addTemplate(page, .5f, 0, 0, .5f, 60, 120);
                }
                document.close();

                ////
                double kilobytes = 0;
                File file1 = new File(sd);
                if (file1.exists()) {

                    double bytes = file1.length();
                    kilobytes = (bytes / 1024);
                    double megabytes = (kilobytes / 1024);
                    double gigabytes = (megabytes / 1024);
                    double terabytes = (gigabytes / 1024);
                    double petabytes = (terabytes / 1024);
                    double exabytes = (petabytes / 1024);
                    double zettabytes = (exabytes / 1024);
                    double yottabytes = (zettabytes / 1024);

                    System.out.println("bytes : " + bytes);
                    System.out.println("kilobytes : " + kilobytes);
                    System.out.println("megabytes : " + megabytes);
                    System.out.println("gigabytes : " + gigabytes);
                    System.out.println("terabytes : " + terabytes);
                    System.out.println("petabytes : " + petabytes);
                    System.out.println("exabytes : " + exabytes);
                    System.out.println("zettabytes : " + zettabytes);
                    System.out.println("yottabytes : " + yottabytes);
                }

                ////

                String[] clus = new String[20];

                int j = 1;
                int k = 0;
                String st = "";

                String extension = ".pdf";


                double Endtime = System.nanoTime();
                double ExeTime = Endtime - starttime;
                db.stmt11.executeUpdate("update jobs set FileName='" + finame + "',StartTime='" + starttime + "',EndTime='" + Endtime + "',JobMemory='" + kilobytes + "',ExecutionTime='" + ExeTime + "',Extension='" + extension + "'  where Type='" + filetype + "'");

                String insertqry = "insert into jobsnew(Type,FileName,StartTime,EndTime,Extension,JobMemory,ExecutionTime )  values('" + filetype + "','" + finame + "','" + starttime + "','" + Endtime + "','" + extension + "','" + kilobytes + "','" + ExeTime + "' )  ";
                db.stmt12.executeUpdate(insertqry);





            } catch (Exception de) {

                de.printStackTrace();
            }


        } else if (cmbtasktype.getSelectedItem().toString().equalsIgnoreCase("IMAGE")) {
            BufferedImage image = null;
            try {


                JFileChooser fc = new JFileChooser();
                fc.setCurrentDirectory(new File("."));
                //fc.addChoosableFileFilter(new OnlyExt());
                fc.setAcceptAllFileFilterUsed(false);

                int returnval = fc.showOpenDialog(null);
                if (returnval == JFileChooser.APPROVE_OPTION) {
                    File file = fc.getSelectedFile();
                    sd = file.getPath();
                    finame = file.getName();

                    System.out.println(sd);
                    System.out.println();
                }


                //you can either use URL or File for reading image using ImageIO
                File imagefile = new File(sd);//"C:\\Cloudspace\\C1.jpg");
                image = ImageIO.read(imagefile);

                //ImageIO Image write Example in Java
                ImageIO.write(image, "jpg", new File("CloudStorage\\" + username + "\\" + "FILES\\" + finame + ".jpg"));
                // ImageIO.write(image, "bmp",new File("C:\\credit_card_loan.bmp"));
                // ImageIO.write(image, "gif",new File("C:\\personal_loan.gif"));
                // ImageIO.write(image, "png",new File("C:\\auto_loan.png"));


                ////////////
                double kilobytes = 0;
                File file1 = new File(sd);
                if (file1.exists()) {

                    double bytes = file1.length();
                    kilobytes = (bytes / 1024);
                    double megabytes = (kilobytes / 1024);
                    double gigabytes = (megabytes / 1024);
                    double terabytes = (gigabytes / 1024);
                    double petabytes = (terabytes / 1024);
                    double exabytes = (petabytes / 1024);
                    double zettabytes = (exabytes / 1024);
                    double yottabytes = (zettabytes / 1024);

                    System.out.println("bytes : " + bytes);
                    System.out.println("kilobytes : " + kilobytes);
                    System.out.println("megabytes : " + megabytes);
                    System.out.println("gigabytes : " + gigabytes);
                    System.out.println("terabytes : " + terabytes);
                    System.out.println("petabytes : " + petabytes);
                    System.out.println("exabytes : " + exabytes);
                    System.out.println("zettabytes : " + zettabytes);
                    System.out.println("yottabytes : " + yottabytes);
                }

                ////

                String[] clus = new String[20];

                int j = 1;
                int k = 0;
                String st = "";

                String extension = ".jpg";


                double Endtime = System.nanoTime();
                double ExeTime = Endtime - starttime;
                try {
                    db.stmt11.executeUpdate("update jobs set FileName='" + finame + "',StartTime='" + starttime + "',EndTime='" + Endtime + "',JobMemory='" + kilobytes + "',ExecutionTime='" + ExeTime + "',Extension='" + extension + "'  where Type='" + filetype + "'");
                    String insertqry = "insert into jobsnew(Type,FileName,StartTime,EndTime,Extension,JobMemory,ExecutionTime )  values('" + filetype + "','" + finame + "','" + starttime + "','" + Endtime + "','" + extension + "','" + kilobytes + "','" + ExeTime + "' )  ";
                    db.stmt12.executeUpdate(insertqry);
                    ///////////
                } catch (SQLException ex) {
                    Logger.getLogger(TASK_CREATION_ENCRYPTION.class.getName()).log(Level.SEVERE, null, ex);
                }


            } catch (IOException e) {
                e.printStackTrace();
            }
            System.out.println("Success");



        } else {
            // String sd="";
            // String finame="";

            JFileChooser fc = new JFileChooser();
            fc.setCurrentDirectory(new File("."));
            //fc.addChoosableFileFilter(new OnlyExt());
            fc.setAcceptAllFileFilterUsed(false);

            int returnval = fc.showOpenDialog(null);
            if (returnval == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                sd = file.getPath();
                finame = file.getName();

                System.out.println(sd);
                System.out.println();
            }
            try {

                String str1 = "";

                BufferedReader br = new BufferedReader(new FileReader(sd));
                String attributeword = "";
                while ((str = br.readLine()) != null) {
                    System.out.println(str);

                    str1 = str1 + str + "\n";               //j++;

                }
                System.out.println("===>" + str1);

                FileWriter fileWriter = new FileWriter("CloudStorage\\" + username + "\\" + "FILES\\" + finame + ".txt");

                BufferedWriter bufferedWriter =
                        new BufferedWriter(fileWriter);

                bufferedWriter.write(str1);

                bufferedWriter.close();


                //////////////////
                double kilobytes = 0;
                File file1 = new File(sd);
                if (file1.exists()) {

                    double bytes = file1.length();
                    kilobytes = (bytes / 1024);
                    double megabytes = (kilobytes / 1024);
                    double gigabytes = (megabytes / 1024);
                    double terabytes = (gigabytes / 1024);
                    double petabytes = (terabytes / 1024);
                    double exabytes = (petabytes / 1024);
                    double zettabytes = (exabytes / 1024);
                    double yottabytes = (zettabytes / 1024);

                    System.out.println("bytes : " + bytes);
                    System.out.println("kilobytes : " + kilobytes);
                    System.out.println("megabytes : " + megabytes);
                    System.out.println("gigabytes : " + gigabytes);
                    System.out.println("terabytes : " + terabytes);
                    System.out.println("petabytes : " + petabytes);
                    System.out.println("exabytes : " + exabytes);
                    System.out.println("zettabytes : " + zettabytes);
                    System.out.println("yottabytes : " + yottabytes);
                }

                ////

                String[] clus = new String[20];

                int j = 1;
                int k = 0;
                String st = "";

                String extension = ".txt";


                double Endtime = System.nanoTime();
                double ExeTime = Endtime - starttime;
                db.stmt11.executeUpdate("update jobs set FileName='" + finame + "',StartTime='" + starttime + "',EndTime='" + Endtime + "',JobMemory='" + kilobytes + "',ExecutionTime='" + ExeTime + "',Extension='" + extension + "'  where Type='" + filetype + "'");
                String insertqry = "insert into jobsnew(Type,FileName,StartTime,EndTime,Extension,JobMemory,ExecutionTime )  values('" + filetype + "','" + finame + "','" + starttime + "','" + Endtime + "','" + extension + "','" + kilobytes + "','" + ExeTime + "' )  ";
                db.stmt12.executeUpdate(insertqry);
                /////////////////
            } catch (Exception exp) {
                exp.printStackTrace();
            }
        }


        try {
            Calendar cal2 = Calendar.getInstance();

            long milliSec1 = cal2.getTimeInMillis();

            try {
                Thread.sleep(500);
            } catch (Exception e) {
                e.printStackTrace();

            }

            Calendar cal = Calendar.getInstance();
            long milliSec2 = cal.getTimeInMillis();

            long timeDifInMilliSec;
            if (milliSec1 >= milliSec2) {
                timeDifInMilliSec = milliSec1 - milliSec2;
            } else {
                timeDifInMilliSec = milliSec2 - milliSec1;
            }

            long timeDifSeconds = timeDifInMilliSec / 1000;
            long timeDifMinutes = timeDifInMilliSec / (60 * 1000);
            long timeDifHours = timeDifInMilliSec / (60 * 60 * 1000);
            long timeDifDays = timeDifInMilliSec / (24 * 60 * 60 * 1000);





            System.out.println(timeDifInMilliSec);
        } catch (Exception expp) {
            expp.printStackTrace();
        }


        JOptionPane.showMessageDialog(null, "Task Created Successfully");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     try {
         // TODO add your handling code here:
         
         String args[] = null;
         Decryption_Homomorphic.main(args);
         decrypt();
     } catch (Exception ex) {
         Logger.getLogger(TASK_CREATION_ENCRYPTION.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_jButton4ActionPerformed
/////////////////////////
    
    // Save ECC Key Pair
private void saveECCKeyPair(KeyPair keyPair, String keyDir) throws IOException {
    try (ObjectOutputStream publicKeyOut = new ObjectOutputStream(new FileOutputStream(keyDir + ".ec.pub"));
         ObjectOutputStream privateKeyOut = new ObjectOutputStream(new FileOutputStream(keyDir + ".ec.priv"))) {
        publicKeyOut.writeObject(keyPair.getPublic());
        privateKeyOut.writeObject(keyPair.getPrivate());
    }
}

// Load ECC Private Key
private PrivateKey loadECCPrivateKey(String keyPath) throws Exception {
    try (ObjectInputStream keyIn = new ObjectInputStream(new FileInputStream(keyPath))) {
        return (PrivateKey) keyIn.readObject();
    }
}

public void encrypt() throws Exception {
    Security.addProvider(new BouncyCastleProvider());

    // Generate AES Key
    KeyGenerator keyGen = KeyGenerator.getInstance("AES");
    keyGen.init(128);
    SecretKey aesKey = keyGen.generateKey();

    // Encrypt File with AES
    Cipher aesCipher = Cipher.getInstance("AES");
    aesCipher.init(Cipher.ENCRYPT_MODE, aesKey);

       String Encryption = "CloudStorage\\" + username + "\\" + "UploadFile\\";
        String filepath =  file.getAbsolutePath();
         System.out.println(filepath);
         
         //String filepath = file.getAbsolutePath();
       // FileInputStream fis = new FileInputStream(file);
         
       // Encrypted file output paths
         encryptedFilePath = filepath.replace("FILES", "VirtualMachine0") + ".enc";
         encryptedKeyPath = filepath.replace("FILES", "VirtualMachine0") + ".des.key.enc";
         signaturePath = filepath.replace("FILES", "VirtualMachine0") + ".file.signature";
    
    try (FileInputStream fis = new FileInputStream(file);
         FileOutputStream fos = new FileOutputStream(encryptedFilePath);
         CipherOutputStream cos = new CipherOutputStream(fos, aesCipher)) {
        byte[] buffer = new byte[1024];
        int bytesRead;
        while ((bytesRead = fis.read(buffer)) != -1) {
            cos.write(buffer, 0, bytesRead);
        }
    }

    // Generate ECC Key Pair and Save It
    KeyPairGenerator ecKeyPairGen = KeyPairGenerator.getInstance("EC", "BC");
    ecKeyPairGen.initialize(new ECGenParameterSpec("secp256r1"));
    KeyPair ecKeyPair = ecKeyPairGen.generateKeyPair();
    saveECCKeyPair(ecKeyPair, encryptedFilePath);

    // Encrypt AES Key using ECC Public Key
    Cipher ecCipher = Cipher.getInstance("ECIES", "BC");
    ecCipher.init(Cipher.ENCRYPT_MODE, ecKeyPair.getPublic());
    byte[] encryptedAesKey = ecCipher.doFinal(aesKey.getEncoded());

    try (FileOutputStream keyOut = new FileOutputStream(encryptedKeyPath)) {
        keyOut.write(encryptedAesKey);
    }

    // Sign the Encrypted File
    Signature signature = Signature.getInstance("SHA256withECDSA", "BC");
    signature.initSign(ecKeyPair.getPrivate());
    try (FileInputStream efis = new FileInputStream(encryptedFilePath)) {
        byte[] buffer = new byte[1024];
        int bytesRead;
        while ((bytesRead = efis.read(buffer)) != -1) {
            signature.update(buffer, 0, bytesRead);
        }
    }
    try (FileOutputStream sigOut = new FileOutputStream(signaturePath)) {
        sigOut.write(signature.sign());
    }

    System.out.println("Encryption completed successfully.");
}

public void decrypt() throws Exception {
    Security.addProvider(new BouncyCastleProvider());

    // Load Encrypted AES Key
    byte[] encryptedAesKey = Files.readAllBytes(Paths.get(encryptedKeyPath));

    // Load ECC Private Key (MUST MATCH ENCRYPTION KEY)
    PrivateKey ecPrivateKey = loadECCPrivateKey(encryptedFilePath + ".ec.priv");

    // Decrypt AES Key
    Cipher ecCipher = Cipher.getInstance("ECIES", "BC");
    ecCipher.init(Cipher.DECRYPT_MODE, ecPrivateKey);
    byte[] aesKeyBytes = ecCipher.doFinal(encryptedAesKey);
    SecretKey aesKey = new SecretKeySpec(aesKeyBytes, "AES");

    // Decrypt the File
    Cipher aesCipher = Cipher.getInstance("AES");
    aesCipher.init(Cipher.DECRYPT_MODE, aesKey);
    try (FileInputStream fis = new FileInputStream(encryptedFilePath);
         FileOutputStream fos = new FileOutputStream(encryptedFilePath.replace(".enc", "_decrypted"));
         CipherOutputStream cos = new CipherOutputStream(fos, aesCipher)) {
        byte[] buffer = new byte[1024];
        int bytesRead;
        while ((bytesRead = fis.read(buffer)) != -1) {
            cos.write(buffer, 0, bytesRead);
        }
    }

    // Verify Signature
    PublicKey ecPublicKey = loadECCPublicKey(encryptedFilePath + ".ec.pub");
    Signature signature = Signature.getInstance("SHA256withECDSA", "BC");
    signature.initVerify(ecPublicKey);

    try (FileInputStream efis = new FileInputStream(encryptedFilePath)) {
        byte[] buffer = new byte[1024];
        int bytesRead;
        while ((bytesRead = efis.read(buffer)) != -1) {
            signature.update(buffer, 0, bytesRead);
        }
    }
    byte[] digitalSignature = Files.readAllBytes(Paths.get(signaturePath));

    if (signature.verify(digitalSignature)) {
        System.out.println("Decryption and signature verification succeeded.");
    } else {
        System.out.println("Signature verification failed!");
    }
}

// Load ECC Public Key
private PublicKey loadECCPublicKey(String keyPath) throws Exception {
    try (ObjectInputStream keyIn = new ObjectInputStream(new FileInputStream(keyPath))) {
        return (PublicKey) keyIn.readObject();
    }
}

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    ////////////////////*
     public void encrypt1() throws Exception {
        //opening streams

      
         Security.addProvider(new BouncyCastleProvider());
        String Encryption = "CloudStorage\\" + username + "\\" + "UploadFile\\";
        String filepath =  file.getAbsolutePath();
         System.out.println(filepath);
         
         //String filepath = file.getAbsolutePath();
       // FileInputStream fis = new FileInputStream(file);
         
       // Encrypted file output paths
         encryptedFilePath = filepath.replace("FILES", "VirtualMachine0") + ".enc";
         encryptedKeyPath = filepath.replace("FILES", "VirtualMachine0") + ".des.key.enc";
         signaturePath = filepath.replace("FILES", "VirtualMachine0") + ".file.signature";


        // Step 1: Generate AES Key (for file encryption)
        KeyGenerator keyGen = KeyGenerator.getInstance("AES");
        keyGen.init(128);  // AES uses a 256-bit key
        SecretKey aesKey = keyGen.generateKey();

        // Step 2: Encrypt the file with AES
        Cipher aesCipher = Cipher.getInstance("AES");
        aesCipher.init(Cipher.ENCRYPT_MODE, aesKey);
        try (FileInputStream fis = new FileInputStream(file);
             FileOutputStream fos = new FileOutputStream(encryptedFilePath);
             CipherOutputStream cos = new CipherOutputStream(fos, aesCipher)) {
            byte[] buffer = new byte[1024];
            int bytesRead;
            while ((bytesRead = fis.read(buffer)) != -1) {
                cos.write(buffer, 0, bytesRead);
            }
        }
       
        
       // Step 3: Generate ECC Key Pair
        KeyPairGenerator ecKeyPairGen = KeyPairGenerator.getInstance("EC", "BC");
        ecKeyPairGen.initialize(new ECGenParameterSpec("secp256r1")); // 256-bit ECC curve (128-bit security)
        KeyPair ecKeyPair = ecKeyPairGen.generateKeyPair();
        PublicKey ecPublicKey = ecKeyPair.getPublic();
        PrivateKey ecPrivateKey = ecKeyPair.getPrivate();

        // Step 4: Encrypt the AES Key using ECC Public Key
        Cipher ecCipher = Cipher.getInstance("ECIES", "BC");
        ecCipher.init(Cipher.ENCRYPT_MODE, ecPublicKey);
        byte[] encryptedAesKey = ecCipher.doFinal(aesKey.getEncoded());

        // Save the encrypted AES key
        try (FileOutputStream keyOut = new FileOutputStream(encryptedKeyPath)) {
            keyOut.write(encryptedAesKey);
        }

        // Step 5: Sign the Encrypted File using ECC Private Key
        Signature signature = Signature.getInstance("SHA256withECDSA", "BC");
        signature.initSign(ecPrivateKey);
        try (FileInputStream efis = new FileInputStream(encryptedFilePath)) {
            byte[] buffer = new byte[1024];
            int bytesRead;
            while ((bytesRead = efis.read(buffer)) != -1) {
                signature.update(buffer, 0, bytesRead);
            }
        }
        byte[] digitalSignature = signature.sign();

        // Save the signature
        try (FileOutputStream sigOut = new FileOutputStream(signaturePath)) {
            sigOut.write(digitalSignature);
        }

        
        System.out.println("File encrypted and signed successfully using Hybrid AES and ECC.");
        
    }
     
     
     
     
     public void decrypt1() throws Exception {
    // Opening streams
    String file1 =TASK_CREATION_ENCRYPTION.encfilename;
    Security.addProvider(new BouncyCastleProvider());
    String Encryption = "CloudStorage\\" + username + "\\" + "UploadFile\\";
    String filepath = encryptedFilePath;
    System.out.println("----********-----"+ filepath);

    // Encrypted file input paths
    String encryptedFilePath = filepath.replace("FILES", "VirtualMachine0") + ".enc";
    String encryptedKeyPath = filepath.replace("FILES", "VirtualMachine0") + ".des.key.enc";
    String signaturePath = filepath.replace("FILES", "VirtualMachine0") + ".file.signature";

    // Step 1: Load the encrypted AES key
    byte[] encryptedAesKey = Files.readAllBytes(Paths.get(encryptedKeyPath));

    // Step 2: Generate ECC Key Pair (for decryption)
    KeyPairGenerator ecKeyPairGen = KeyPairGenerator.getInstance("EC", "BC");
    ecKeyPairGen.initialize(new ECGenParameterSpec("secp256r1"));
    KeyPair ecKeyPair = ecKeyPairGen.generateKeyPair();
    PublicKey ecPublicKey = ecKeyPair.getPublic();
    PrivateKey ecPrivateKey = ecKeyPair.getPrivate();

    // Step 3: Decrypt the AES key using the ECC Private Key
    Cipher ecCipher = Cipher.getInstance("ECIES", "BC");
    ecCipher.init(Cipher.DECRYPT_MODE, ecPrivateKey);
    byte[] aesKeyBytes = ecCipher.doFinal(encryptedAesKey);
    SecretKey aesKey = new SecretKeySpec(aesKeyBytes, "AES");

    // Step 4: Decrypt the file using AES
    Cipher aesCipher = Cipher.getInstance("AES");
    aesCipher.init(Cipher.DECRYPT_MODE, aesKey);
    try (FileInputStream fis = new FileInputStream(encryptedFilePath);
         FileOutputStream fos = new FileOutputStream(filepath.replace(".enc", "_decrypted"));
         CipherOutputStream cos = new CipherOutputStream(fos, aesCipher)) {
        byte[] buffer = new byte[1024];
        int bytesRead;
        while ((bytesRead = fis.read(buffer)) != -1) {
            cos.write(buffer, 0, bytesRead);
        }
    }

    // Step 5: Verify the signature (optional)
    Signature signature = Signature.getInstance("SHA256withECDSA", "BC");
    signature.initVerify(ecPublicKey);
    try (FileInputStream efis = new FileInputStream(encryptedFilePath)) {
        byte[] buffer = new byte[1024];
        int bytesRead;
        while ((bytesRead = efis.read(buffer)) != -1) {
            signature.update(buffer, 0, bytesRead);
        }
    }
    byte[] digitalSignature = Files.readAllBytes(Paths.get(signaturePath));
    boolean isVerified = signature.verify(digitalSignature);

    if (isVerified) {
        System.out.println("File decrypted and signature verified successfully.");
    } else {
        System.out.println("Signature verification failed.");
    }
}

     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TASK_CREATION_ENCRYPTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TASK_CREATION_ENCRYPTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TASK_CREATION_ENCRYPTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TASK_CREATION_ENCRYPTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TASK_CREATION_ENCRYPTION().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox cmbtasktype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
